version: '3.5'

services:
  db_main:
    container_name: db_main
    restart: unless-stopped
    image: postgres:14.3-alpine
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres_main:/var/lib/postgresql/data

  db_subscriber:
    container_name: db_subscriber
    restart: unless-stopped
    image: postgres:14.3-alpine
    ports:
      - 5433:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_MAIN}

    volumes:
      - postgres_subscriber:/var/lib/postgresql/data

volumes:
  postgres_main:
  postgres_subscriber:
