version: '3'

services:
  db_app:
   container_name: db_postgres
   restart: unless-stopped
   image: postgres:14.3-alpine
   environment:
     - POSTGRES_USER=${POSTGRES_USER}
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     - POSTGRES_DB=${POSTGRES_DB}
   ports:
     - ${POSTGRES_PORT}:${POSTGRES_PORT}


volumes:
  db_data:
     
   