version: '3'

services:
  
  rabbitmq:
    container_name: rabbitmq
    restart: unless-stopped
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    ports:
      - "15672:15672"
      - "5672:5672"


  db_app:
   container_name: db_postgres
   restart: unless-stopped
   image: postgres:14.3-alpine
   environment:
     - POSTGRES_USER=${POSTGRES_USER}
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     - POSTGRES_DB=${POSTGRES_DB}
   ports:
     - ${POSTGRES_PORT}:${POSTGRES_PORT}


volumes:
  db_data:
     
   